### PR TITLE
Proposed updates to System Console settings page

### PR DESCRIPTION
**Pull request by jasonblais**
First, HUGE thanks for your work on the plugin. Starting testing now, reviewed the System Console page to start.

I'm aware this requires some code changes, but I wanted to summarize proposed changes through changes in the plugin.json manifest:

1. Change the first setting to a radio option between Online and Server products. This makes it more obvious which options are supported.
2. Update help texts for username, password and domain fields.
3. Move "Application ID" to the bottom. This keeps all Server settings at the top which is more likely to be used for a product type. 
4. Move the Azure Active Directory URL as part of the setting help text.
5. Update text for footer

Note that all proposed changes are up for feedback 👍 

Questions:

6. For Skype4Business Server, I saw some discussion about using bot accounts. Is this planned in the long term?
7. Related to 6, I don't think storing the username and password in plain text fields is acceptable security-wise. So if we won't use bot accounts, do we have another approach we can use instead?

### CODE REVIEW

**Comment by kosgrz** [comment]
@jasonblais, Thanks for the PR!
> For Skype4Business Server, I saw some discussion about using bot accounts. Is this planned in the long term?

By bot accounts, I meant accounts created on Skype for Business Server. Their credentials are used to create meetings in S4B. Unfortunately, I don't see any better solution to use with S4B Server.
Of course, I can also implement the usage of bot accounts in MM, it wouldn't be a big problem.

> Related to 6, I don't think storing the username and password in plain text fields is acceptable security-wise. So if we won't use bot accounts, do we have another approach we can use instead?

Yes, this definitely needs fixes. Unfortunately, in the [documentation](https://developers.mattermost.com/extend/plugins/manifest-reference/#settings_schema.settings.type) I don't see more suitable types of fields to use in that case :/

**Comment by jasonblais** [comment]
@kosgrz Ah, I see. These are bot accounts created on Skype for Business Server, used to connect to Mattermost.

Do you know if S4B provides a token or other way of connecting with that bot account?

**Comment by kosgrz** [comment]
@jasonblais this is very strange, but S4B doesn't provide tokens like in many other APIs. There is the official [documentation](https://docs.microsoft.com/en-us/skype-sdk/ucwa/authenticationinucwa) about the authentication process. I have two other solutions that come to my mind:
1. I could use the passive authentication method. From the description, I see that it looks quite similar to the method used by the S4B Online. User needs to sign in on an external website and after that, they receive a token that could be used by the plugin to create a meeting. The downside of that solution is that it's quite difficult to implement.
2. I can implement the password method in another way. After the user clicks a button, a popup with input to pass the password for S4B is shown. When the user submits the form, plugin receives their password and sends it to S4B Server. S4B Server in response returns a token which is stored in our database. We could use this token to create meetings on behalf of the user for 8 hours. After that, the token is expired and the user needs to submit the password again if they want to create a new meeting.

**Comment by jasonblais** [comment]
Thanks @kosgrz. I remember the second option was discussed previously in Mattermost as well.

Let me post a follow up in the Skype4Business channel 👍

**Comment by jasonblais** [comment]
6 + 7 resolved by updating help text. For further context, see https://community.mattermost.com/core/pl/tbwx6uxo9ty8fczi47zmgeqh4w

**Comment by kosgrz** [comment]
Great! In that situation, I approve the PR. Thanks!

**Comment by jasonblais** [comment]
Thanks @kosgrz! I should have noted that I didn't test the changes locally, so it'll be good to verify everything still works as expected 🙏

**Comment by kosgrz** [comment]
@jasonblais no problem, I've just uploaded the commit https://github.com/kosgrz/mattermost-plugin-skype4business/commit/7ed19e14203f8f1650ec7a0a576f7a6bc6d85faf which adjusts the code to the new manifest file.

**Comment by jasonblais** [comment]
Yay, awesome! 👍

**Pull request merged**
